import { useEffect, useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, CheckCircle2, ClipboardList, Eye, FileText, Plus, RefreshCw, Search, ShieldCheck, UserCheck, XCircle } from 'lucide-react'
import { PageHeader } from '../../components/layout/PageHeader'
import { StatusBadge } from '../../components/status/StatusBadge'
import { Button } from '../../lib/shadcn/button'
import { toast } from '../../lib/shadcn/sonner'
import { supabase } from '../../lib/supabase'

const input='h-9 w-full rounded-md border border-border bg-background px-2.5 text-sm outline-none focus:ring-1 focus:ring-ring'
const area='min-h-24 w-full rounded-md border border-border bg-background px-2.5 py-2 text-sm outline-none focus:ring-1 focus:ring-ring'
const err=(e:unknown)=>e instanceof Error?e.message:'Operation failed'
const statuses=['submitted','under_review','needs_more_evidence','verified','rejected','resolved'] as const
const categories=['withdrawal_issues','account_closures','unpaid_winnings','kyc_verification','payment_issues','bonus_disputes','bet_settlement','support_communication','other']
const severities=['low','moderate','high','critical']
const evidenceStrengths=['limited','moderate','strong']

type Report={id:string;reference_code:string;bookmaker_id:string|null;custom_brand_name:string|null;custom_brand_url:string|null;submitted_by:string;player_name:string|null;username:string|null;phone:string|null;account_id:string|null;contact_email:string|null;category:string;incident_date:string;description:string;amount:number|null;currency:string|null;payment_method:string|null;transaction_reference:string|null;closure_reason:string|null;verification_type:string|null;bet_reference:string|null;stake_amount:number|null;expected_winnings:number|null;bonus_name:string|null;support_channel:string|null;accuracy_confirmed:boolean;status:string;admin_notes:string|null;reviewed_by:string|null;reviewed_at:string|null;rejected_reason:string|null;submitted_at:string;created_at:string;updated_at:string;bookmakers_radar:any;bookmaker_report_evidence:any[];bookmaker_incidents:any[]}

type Incident={id:string;report_id:string;bookmaker_id:string;title:string;category:string;incident_date:string;verified_at:string;published_at:string;severity:string;evidence_strength:string;summary:string;amount:number|null;currency:string|null;resolution_status:string;resolution_note:string|null;resolved_at:string|null;resolved_by:string|null;verified_by:string|null}

function Card({title,children,actions}:{title:string;children:React.ReactNode;actions?:React.ReactNode}){return <section className="rounded-lg border border-border bg-card p-density-lg shadow-retool-sm"><div className="mb-density-md flex items-center justify-between gap-3"><h2 className="text-base font-semibold">{title}</h2>{actions}</div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="flex flex-col gap-1.5 text-xs font-medium text-muted-foreground"><span>{label}</span>{children}</label>}
function Empty({children}:{children:React.ReactNode}){return <div className="py-7 text-center text-sm text-muted-foreground">{children}</div>}
function fmt(v:any){return v===null||v===undefined||v===''?'—':String(v)}
function date(v:any){return v?new Date(v).toLocaleString():'—'}
function arr<T=any>(v:any):T[]{return Array.isArray(v)?v:v?[v]:[]}

export default function BookmakerReports(){
 const {id:routeId}=useParams();
 const [reports,setReports]=useState<Report[]>([]); const [bookmakers,setBookmakers]=useState<any[]>([]); const [selectedId,setSelectedId]=useState(routeId||'');
 const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [statusFilter,setStatusFilter]=useState('all'); const [categoryFilter,setCategoryFilter]=useState('all');
 const [draftStatus,setDraftStatus]=useState(''); const [adminNotes,setAdminNotes]=useState(''); const [rejectedReason,setRejectedReason]=useState(''); const [saving,setSaving]=useState(false);
 const [matchId,setMatchId]=useState(''); const [matching,setMatching]=useState(false);
 const [publication,setPublication]=useState({title:'',summary:'',severity:'moderate',evidence_strength:'moderate',resolution_status:'unresolved',amount:'',currency:''});
 const [publishing,setPublishing]=useState(false); const [resolving,setResolving]=useState(false); const [resolutionNote,setResolutionNote]=useState('');
 const [summary,setSummary]=useState<any>(null); const [audit,setAudit]=useState<any[]>([]);

 const load=async()=>{setLoading(true);try{
   const [rr,bb]=await Promise.all([
     supabase.from('bookmaker_reports').select('*,bookmakers_radar(id,name,slug,status,radar_score,risk_level,confidence_level,evidence_strength,current_signal,trend,verified_reports,unresolved_reports,resolved_reports,repeated_patterns,radar_computed_at),bookmaker_report_evidence(id,storage_path,original_filename,mime_type,file_size,evidence_type,uploaded_by,metadata,created_at),bookmaker_incidents(id,report_id,bookmaker_id,title,category,incident_date,verified_at,published_at,severity,evidence_strength,summary,amount,currency,resolution_status,resolution_note,resolved_at,resolved_by,verified_by)').order('submitted_at',{ascending:false}),
     supabase.from('bookmakers_radar').select('id,name,slug,status,radar_score,risk_level').order('name')
   ]);
   if(rr.error) throw rr.error; if(bb.error) throw bb.error;
   const data=(rr.data??[]) as Report[]; setReports(data); setBookmakers(bb.data??[]);
   if(!selectedId && data[0]) setSelectedId(data[0].id);
   if(selectedId && !data.some(r=>r.id===selectedId) && data[0]) setSelectedId(data[0].id);
 }catch(e){toast.error(err(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(routeId) setSelectedId(routeId)},[routeId]);
 useEffect(()=>{const t=window.setInterval(()=>void load(),30000);return()=>window.clearInterval(t)},[selectedId]);

 const filtered=useMemo(()=>reports.filter(r=>{
   const q=query.trim().toLowerCase(); const hit=!q||[r.reference_code,r.custom_brand_name,r.description,r.username,r.player_name,r.contact_email,r.bookmakers_radar?.name].filter(Boolean).some(x=>String(x).toLowerCase().includes(q));
   return hit&&(statusFilter==='all'||r.status===statusFilter)&&(categoryFilter==='all'||r.category===categoryFilter)
 }),[reports,query,statusFilter,categoryFilter]);
 const selected=reports.find(r=>r.id===selectedId)??filtered[0]??null; const incident=selected?((arr<Incident>(selected.bookmaker_incidents)[0])??null):null;

 useEffect(()=>{if(!selected)return; setDraftStatus(selected.status);setAdminNotes(selected.admin_notes??'');setRejectedReason(selected.rejected_reason??'');setMatchId(selected.bookmaker_id??''); const i=incident; setPublication({title:i?.title??`${selected.category.replaceAll('_',' ')} report`,summary:i?.summary??selected.description,severity:i?.severity??'moderate',evidence_strength:i?.evidence_strength??'moderate',resolution_status:i?.resolution_status??'unresolved',amount:i?.amount!=null?String(i.amount):selected.amount!=null?String(selected.amount):'',currency:i?.currency??selected.currency??''});setResolutionNote(i?.resolution_note??'');
   void (async()=>{const {data,error}=await supabase.from('bookmaker_radar_audit_log').select('*').eq('entity_id',selected.id).order('created_at',{ascending:false}).limit(25);if(!error)setAudit(data??[]);else setAudit([]);})();
   if(selected.bookmaker_id){void (async()=>{const {data}=await supabase.rpc('get_bookmaker_radar_summary',{p_bookmaker_id:selected.bookmaker_id});setSummary(data??null)})()}else setSummary(null);
 },[selectedId,reports.length]);

 const saveReview=async()=>{if(!selected)return;setSaving(true);try{const {error}=await supabase.rpc('admin_update_bookmaker_report',{p_report_id:selected.id,p_status:draftStatus,p_admin_notes:adminNotes||null,p_rejected_reason:rejectedReason||null});if(error)throw error;toast.success('Report review state saved');await load()}catch(e){toast.error(err(e))}finally{setSaving(false)}};
 const matchReport=async()=>{if(!selected||!matchId)return;setMatching(true);try{const {error}=await supabase.from('bookmaker_reports').update({bookmaker_id:matchId}).eq('id',selected.id);if(error)throw error;toast.success('Report matched to bookmaker');await load()}catch(e){toast.error(err(e))}finally{setMatching(false)}};
 const createFromCustom=async()=>{if(!selected?.custom_brand_name)return;setMatching(true);try{const {data,error}=await supabase.rpc('find_or_create_bookmaker',{p_name:selected.custom_brand_name,p_website:selected.custom_brand_url||null});if(error)throw error;const bookmakerId=data?.id;if(!bookmakerId)throw new Error('Bookmaker creation returned no id');const {error:ue}=await supabase.from('bookmaker_reports').update({bookmaker_id:bookmakerId}).eq('id',selected.id);if(ue)throw ue;toast.success('Bookmaker created/matched and report linked');await load()}catch(e){toast.error(err(e))}finally{setMatching(false)}};
 const publish=async()=>{if(!selected)return;setPublishing(true);try{const {error}=await supabase.rpc('admin_publish_bookmaker_report',{p_report_id:selected.id,p_title:publication.title.trim(),p_summary:publication.summary.trim(),p_severity:publication.severity,p_evidence_strength:publication.evidence_strength,p_resolution_status:publication.resolution_status,p_amount:publication.amount===''?null:Number(publication.amount),p_currency:publication.currency||null});if(error)throw error;toast.success('Report published to Radar incidents');await load()}catch(e){toast.error(err(e))}finally{setPublishing(false)}};
 const resolve=async()=>{if(!incident)return;setResolving(true);try{const {error}=await supabase.rpc('admin_resolve_bookmaker_incident',{p_incident_id:incident.id,p_resolution_note:resolutionNote||null});if(error)throw error;toast.success('Incident resolved and Radar recomputed');await load()}catch(e){toast.error(err(e))}finally{setResolving(false)}};
 const recompute=async()=>{if(!selected?.bookmaker_id)return;const {error}=await supabase.rpc('recompute_bookmaker_radar',{p_bookmaker_id:selected.bookmaker_id});if(error)toast.error(err(error));else{toast.success('Radar recomputed');await load()}};

 const stats={total:reports.length,pending:reports.filter(r=>['submitted','under_review'].includes(r.status)).length,evidence:reports.filter(r=>r.status==='needs_more_evidence').length,verified:reports.filter(r=>['verified','resolved'].includes(r.status)).length,unresolved:reports.filter(r=>arr<Incident>(r.bookmaker_incidents).some(i=>i.resolution_status==='unresolved')).length};
 return <div className="flex flex-col gap-density-lg">
   <PageHeader title="Bookmaker Reports" description="Admin intake, review, bookmaker matching, evidence review, publication, incident resolution and Radar audit." actions={<><Button variant="outline" onClick={()=>void load()} disabled={loading}><RefreshCw className="h-4 w-4"/>Refresh</Button><Button asChild><Link to="/bookmakersradar"><ShieldCheck className="h-4 w-4"/>Directory</Link></Button></>}/>
   <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5"><Metric label="Total reports" value={stats.total}/><Metric label="Needs review" value={stats.pending}/><Metric label="Needs evidence" value={stats.evidence}/><Metric label="Verified / resolved" value={stats.verified}/><Metric label="Open incidents" value={stats.unresolved}/></div>
   <div className="grid gap-density-lg xl:grid-cols-[minmax(420px,0.9fr)_minmax(0,1.6fr)]">
     <Card title="Incoming reports" actions={<span className="text-xs text-muted-foreground">{filtered.length} shown</span>}>
       <div className="mb-density-md grid gap-2 md:grid-cols-2"><div className="relative"><Search className="absolute left-2.5 top-2 h-4 w-4 text-muted-foreground"/><input className={`${input} pl-8`} placeholder="Reference, player, bookmaker…" value={query} onChange={e=>setQuery(e.target.value)}/></div><select className={input} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><select className={input} value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
       <div className="max-h-[760px] overflow-y-auto pr-1">{filtered.length?filtered.map(r=><button key={r.id} className={`mb-2 w-full rounded-md border p-3 text-left transition ${selected?.id===r.id?'border-ring bg-muted/50':'border-border hover:bg-muted/30'}`} onClick={()=>setSelectedId(r.id)}><div className="flex items-start justify-between gap-2"><div><div className="font-medium">{r.bookmakers_radar?.name??r.custom_brand_name??'Unmatched bookmaker'}</div><div className="font-mono text-xs text-muted-foreground">{r.reference_code}</div></div><StatusBadge status={r.status} dense/></div><div className="mt-2 text-xs text-muted-foreground">{r.category} · incident {r.incident_date} · submitted {date(r.submitted_at)}</div><p className="mt-2 line-clamp-2 text-sm">{r.description}</p><div className="mt-2 flex gap-2 text-[11px] text-muted-foreground"><span>{arr(r.bookmaker_report_evidence).length} evidence</span><span>•</span><span>{arr(r.bookmaker_incidents).length} incident</span></div></button>):<Empty>{loading?'Loading reports…':'No reports match the current filters.'}</Empty>}</div>
     </Card>
     {selected?<div className="flex flex-col gap-density-lg">
       <Card title={`${selected.reference_code} · Report detail`} actions={<div className="flex gap-2"><StatusBadge status={selected.status} dense/><Button size="sm" variant="outline" onClick={()=>void saveReview()} disabled={saving}><CheckCircle2 className="h-3.5 w-3.5"/>Save review</Button></div>}>
         <div className="grid gap-density-md md:grid-cols-2 xl:grid-cols-3"><Info label="Bookmaker" value={selected.bookmakers_radar?.name??selected.custom_brand_name??'Unmatched'}/><Info label="Category" value={selected.category}/><Info label="Incident date" value={selected.incident_date}/><Info label="Submitted" value={date(selected.submitted_at)}/><Info label="Player" value={selected.player_name}/><Info label="Username" value={selected.username}/><Info label="Contact" value={selected.contact_email}/><Info label="Account ID" value={selected.account_id}/><Info label="Amount" value={selected.amount!=null?`${selected.amount} ${selected.currency??''}`:null}/><Info label="Payment method" value={selected.payment_method}/><Info label="Transaction ref" value={selected.transaction_reference}/><Info label="Bet reference" value={selected.bet_reference}/></div>
         <div className="mt-density-md rounded-md border border-border bg-muted/20 p-3"><div className="mb-1 text-xs font-semibold text-muted-foreground">Player statement</div><div className="whitespace-pre-wrap text-sm">{selected.description}</div></div>
         <div className="mt-density-md grid gap-density-md md:grid-cols-3"><Field label="Review status"><select className={input} value={draftStatus} onChange={e=>setDraftStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Admin notes"><textarea className={area} value={adminNotes} onChange={e=>setAdminNotes(e.target.value)}/></Field><Field label="Rejected reason"><textarea className={area} value={rejectedReason} onChange={e=>setRejectedReason(e.target.value)}/></Field></div>
       </Card>
       <Card title="Bookmaker matching" actions={<span className="text-xs text-muted-foreground">Match before publication</span>}>
         <div className="grid gap-density-md md:grid-cols-[1fr_auto]"><Field label="Directory bookmaker"><select className={input} value={matchId} onChange={e=>setMatchId(e.target.value)}><option value="">Select bookmaker…</option>{bookmakers.map(b=><option key={b.id} value={b.id}>{b.name} · {b.slug} · {b.status}</option>)}</select></Field><div className="flex items-end gap-2"><Button onClick={()=>void matchReport()} disabled={!matchId||matching}><UserCheck className="h-4 w-4"/>Match</Button>{selected.custom_brand_name&&!selected.bookmaker_id?<Button variant="outline" onClick={()=>void createFromCustom()} disabled={matching}><Plus className="h-4 w-4"/>Create from report</Button>:null}</div></div>
         {selected.bookmakers_radar?<div className="mt-density-md rounded-md border border-border p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-medium">{selected.bookmakers_radar.name}</div><div className="text-xs text-muted-foreground">{selected.bookmakers_radar.slug}</div></div><div className="flex gap-2"><Button asChild size="sm" variant="outline"><Link to={`/bookmakersradar/${selected.bookmakers_radar.id}/edit`}>Edit bookmaker</Link></Button><Button size="sm" variant="outline" onClick={()=>void recompute()}><RefreshCw className="h-3.5 w-3.5"/>Recompute</Button></div></div><div className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-5"><Info label="Radar score" value={selected.bookmakers_radar.radar_score}/><Info label="Risk" value={selected.bookmakers_radar.risk_level}/><Info label="Confidence" value={selected.bookmakers_radar.confidence_level}/><Info label="Signal" value={selected.bookmakers_radar.current_signal}/><Info label="Trend" value={selected.bookmakers_radar.trend}/></div></div>:<div className="mt-density-md rounded-md border border-dashed border-border p-4 text-sm text-muted-foreground">This report is not linked to a directory bookmaker yet. Use the match controls above.</div>}
       </Card>
       <Card title="Evidence" actions={<span className="text-xs text-muted-foreground">{arr(selected.bookmaker_report_evidence).length} item(s)</span>}>
         {arr(selected.bookmaker_report_evidence).length?arr(selected.bookmaker_report_evidence).map((e:any)=><div key={e.id} className="mb-2 flex items-center justify-between rounded-md border border-border p-3"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-muted-foreground"/><div><div className="font-medium">{e.original_filename??e.storage_path}</div><div className="text-xs text-muted-foreground">{e.evidence_type} · {e.mime_type??'unknown'} · {e.file_size??'—'} bytes · {date(e.created_at)}</div></div></div><Button size="sm" variant="ghost"><Eye className="h-3.5 w-3.5"/>Metadata</Button></div>):<Empty>No evidence attached to this report.</Empty>}
       </Card>
       <div className="grid gap-density-lg xl:grid-cols-2">
         <Card title="Publish to Radar incident" actions={<span className="text-xs text-muted-foreground">Creates verified incident + recomputes Radar</span>}>
           <div className="grid gap-density-md md:grid-cols-2"><Field label="Title"><input className={input} value={publication.title} onChange={e=>setPublication({...publication,title:e.target.value})}/></Field><Field label="Severity"><select className={input} value={publication.severity} onChange={e=>setPublication({...publication,severity:e.target.value})}>{severities.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Evidence strength"><select className={input} value={publication.evidence_strength} onChange={e=>setPublication({...publication,evidence_strength:e.target.value})}>{evidenceStrengths.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Resolution status"><select className={input} value={publication.resolution_status} onChange={e=>setPublication({...publication,resolution_status:e.target.value})}><option>unresolved</option><option>resolved</option></select></Field><Field label="Amount"><input className={input} type="number" value={publication.amount} onChange={e=>setPublication({...publication,amount:e.target.value})}/></Field><Field label="Currency"><input className={input} value={publication.currency} onChange={e=>setPublication({...publication,currency:e.target.value})}/></Field></div><div className="mt-density-md grid gap-density-md"><Field label="Published title"><input className={input} value={publication.title} onChange={e=>setPublication({...publication,title:e.target.value})}/></Field><Field label="Public summary"><textarea className={area} value={publication.summary} onChange={e=>setPublication({...publication,summary:e.target.value})}/></Field></div><div className="mt-density-md flex justify-end"><Button onClick={()=>void publish()} disabled={publishing||!selected.bookmaker_id||!publication.title.trim()||!publication.summary.trim()||!['verified','under_review'].includes(selected.status)}><ClipboardList className="h-4 w-4"/>{publishing?'Publishing…':'Publish verified incident'}</Button></div><div className="mt-2 text-xs text-muted-foreground">Backend publication requires a linked bookmaker and report status <b>verified</b> or <b>under_review</b>.</div>
         </Card>
         <Card title="Incident resolution" actions={incident?<StatusBadge status={incident.resolution_status} dense/>:undefined}>{incident?<><div className="grid gap-density-md md:grid-cols-2"><Info label="Incident" value={incident.title}/><Info label="Severity" value={incident.severity}/><Info label="Evidence" value={incident.evidence_strength}/><Info label="Verified" value={date(incident.verified_at)}/></div><div className="mt-density-md"><Field label="Resolution note"><textarea className={area} value={resolutionNote} onChange={e=>setResolutionNote(e.target.value)}/></Field></div><div className="mt-density-md flex justify-end"><Button variant="outline" onClick={()=>void resolve()} disabled={resolving||incident.resolution_status==='resolved'}>{resolving?'Resolving…':'Resolve incident'}</Button></div></>:<Empty>No incident exists for this report yet.</Empty>}</Card>
       </div>
       <Card title="Radar evidence & criteria">{summary?.criteria?.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-border text-left text-xs text-muted-foreground"><th className="py-2">Category</th><th>Verified cases</th><th>Unresolved</th><th>Resolved</th></tr></thead><tbody>{summary.criteria.map((c:any)=><tr key={c.category} className="border-b border-border/70"><td className="py-2">{c.category}</td><td>{c.verified_cases}</td><td>{c.unresolved}</td><td>{c.resolved}</td></tr>)}</tbody></table></div>:<Empty>No verified Radar criteria yet.</Empty>}{summary?.incidents?.length?<div className="mt-density-md grid gap-2 md:grid-cols-2">{summary.incidents.map((i:any)=><div key={i.id} className="rounded-md border border-border p-3"><div className="flex justify-between gap-2"><div className="font-medium">{i.title}</div><StatusBadge status={i.resolution_status} dense/></div><div className="mt-1 text-xs text-muted-foreground">{i.category} · {i.severity} · {i.evidence_strength}</div><div className="mt-2 text-sm">{i.summary}</div></div>)}</div>:null}</Card>
       <Card title="Radar audit trail" actions={<span className="text-xs text-muted-foreground">Last 25 report events</span>}>{audit.length?audit.map(a=><div key={a.id} className="mb-2 grid gap-1 rounded-md border border-border p-3 md:grid-cols-[170px_1fr_170px]"><div className="font-medium">{a.action}</div><div className="text-xs text-muted-foreground">{a.entity_type} · {a.entity_id}</div><div className="text-right text-xs text-muted-foreground">{date(a.created_at)}</div></div>):<Empty>No audit events found for this report.</Empty>}</Card>
     </div>:<Card title="Report detail"><Empty>Select a report to inspect and process it.</Empty></Card>}
   </div>
 </div>
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-lg border border-border bg-card p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold">{value.toLocaleString()}</div></div>}
function Info({label,value}:{label:string;value:any}){return <div><div className="text-xs text-muted-foreground">{label}</div><div className="mt-0.5 text-sm font-medium">{fmt(value)}</div></div>}
