FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY workers /app/workers

RUN pip install --no-cache-dir -r /app/workers/archive_worker/requirements.txt

CMD ["python", "-m", "workers.provider_gateway.worker"]
